dist: xenial
sudo: false
addons:
  apt:
    packages:
      - libgtk-3-dev
      - libatk1.0-dev
      - libpango1.0-dev
      - libdbus-1-dev
      - libzmq3-dev
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:    
    - rust: nightly
